# Add 'repo' label to any root file changes
normal:
  - '*'

# Add 'docs' label to any changes to the docs folder
docs:
  - 'docs/**'

# Add 'tests' label to any changes to the tests folder
tests:
  - 'tests/**'

# Add 'ci' label to any changes to the .github folder
ci:
  - '.github/**'

# Add 'dependencies' label to any changes to package.json or package-lock.json
dependencies:
  - 'package.json'
  - 'package-lock.json'
  - 'yarn.lock'

# Add 'eslint' label to any changes to .eslintrc.json or .eslintignore
eslint:
  - '.eslintrc.json'
  - '.eslintignore'

# Add 'prettier' label to any changes to .prettierrc.json or .prettierignore
prettier:
  - '.prettierrc.json'
  - '.prettierignore'

# Add 'typescript' label to any changes to tsconfig.json
typescript:
  - 'tsconfig.json'

# Add 'webpack' label to any changes to webpack.config.js
webpack:
  - 'webpack.config.js'

# Add 'babel' label to any changes to .babelrc.json
babel:
  - '.babelrc.json'

# Add 'android' label to any changes in the android folder
android:
  - 'android/**'

# Add 'ios' label to any changes in the ios folder
ios:
  - 'ios/**'

# Add 'react-native' label to any changes in the src or components folder
react-native:
  - 'src/**'
  - 'components/**'
  
# Add 'assets' label to any changes in the assets folder
assets:
  - 'assets/**'

# Add 'styles' label to any changes in the styles folder
styles:
  - 'styles/**'
